name: Bundle Archives

on:
  push:
    branches:
      - "v*"

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: v14.x
    - run: npm i
      name: Install dependencies
    - run: tar czf ../powercord.tar.gz .
      name: Make archive
    - run: mv ../powercord.tar.gz .
    - name: Update release
      uses: softprops/action-gh-release@v1
      with:
        files: powercord.tar.gz
